package com.bank.bian.partyreferencedatadirectory;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Party Reference Data Directory
 *
 * Business Area:      Reference Data
 * Business Domain:    Reference Data
 * Functional Pattern: Catalog
 * Asset Type:         Party Reference Data
 * Control Record:     Party Reference Data Directory Entry
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Party Reference Data Directory — BIAN Semantic API")
                .description("Service Domain 'Party Reference Data Directory' (Catalog pattern) "
                        + "operating on the 'Party Reference Data Directory Entry' control record.")
                .version("0.1.0"));
    }
}
